

resources:
  repositories:
    - repository: 'templates'
      type: 'git'
      name: 'SPRINGBOOT-VALIDATION'

trigger:
  branches:
    include:
      - refs/heads/main

pr: 'none'

pool:
  vmImage: 'ubuntu-latest'

variables: 
  - template: 'azure-pipelines.yml'

stages: 
  - stage: 'Build'
    displayName: Create Docker vmImage
    jobs:
      - template: templates/maven.yaml@templates
        parameters: 
          vabriableFiles: zaure-pipelines.yaml@self